version: "3.8"
services:

  ghost:
    image: ghost:alpine
    ports:
       - 8080:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
    links:
      - db

  db:
    image: mysql:5.7.26
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password


volumes:
  db-data: